apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-sample
  template:
    metadata:
      labels:
        app: java-sample
    spec:
      containers:
        - name: java-sample
          image: SaraIravani/#java-sample-pipeline:1.0.0-9
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
