apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-sample
  template:
    metadata:
      labels:
        app: java-sample
    spec:
      containers:
        - name: java-sample
          image: SaraIravani/java-sample-ci:1.0.0-30
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20  
