apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-deployment
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
    description: "Java Sample Application Deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-sample
  template:
    metadata:
      labels:
        app: java-sample
    spec:
      containers:
        - name: java-sample
          image: sarairavani/java-sample-ci:1.0.0-30
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:  
            - name: JAVA_OPTS
              value: "-Xmx200m -Xms100m"    
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20     
