apiVersion: v1
kind: Service
metadata:
  name: java-sample-service
  labels:
    app: java-sample 
spec:
  selector:
    app: java-sample

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
